### ISSUE TITLE
How to skip sign up and login

### ISSUE THREAD

**Issue by knzcx** [kpi88/chatbot-docker#3]
To test it locally, I do not necessarily need a login or registration. Is there a way to skip this step? Or am I missing something. I was able to start everything locally via docker compose.

If I still try to register via e-mail, I get the following error message:
```
supabase_chat.gpt.local.gpt.local_chatbotui  | `x-forwarded-host` header with value `chat.gpt.local.gpt.local` does not match `origin` header with value `gpt.local` from a forwarded Server Actions request. Aborting the action.
supabase_chat.gpt.local.gpt.local_chatbotui  | Error: Invalid Server Actions request.
supabase_chat.gpt.local.gpt.local_chatbotui  |     at rg (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:5848)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at rz (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:24715)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27397
supabase_chat.gpt.local.gpt.local_chatbotui  |     at AsyncLocalStorage.run (node:async_hooks:346:14)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at Object.wrap (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:16207)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27287
supabase_chat.gpt.local.gpt.local_chatbotui  |     at AsyncLocalStorage.run (node:async_hooks:346:14)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at Object.wrap (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:13:15455)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at rV (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:27214)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at ni.render (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:31187)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at doRender (/app/node_modules/next/dist/server/base-server.js:1394:44)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1555:34)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at ResponseCache.get (/app/node_modules/next/dist/server/response-cache/index.js:49:26)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1463:53)
supabase_chat.gpt.local.gpt.local_chatbotui  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

My /etc/hosts config:
`127.0.0.1 gpt.local supabase.gpt.local chat.gpt.local studio.gpt.local`

My domain config via `.env`:
```
DOMAIN="gpt.local"
SUPABASE_SUBDOMAIN="supabase.gpt.local"
CHATBOTUI_SUBDOMAIN="chat.gpt.local"
STUDIO_SUBDOMAIN="studio.gpt.local"
SCHEME="http"
# docker resolver
RESOLVER="127.0.0.11"
# podman resolver
#RESOLVER="10.88.0.1"
```

![SCR-20240321-rtjb](https://github.com/kpi88/chatbot-docker/assets/77453174/e34d2f84-dc93-4906-bc4c-8e2f29390763)

**Comment by knzcx** [comment]
Nvm, my head is too tired. Got it right now. Thanks for providing this setup!
![SCR-20240321-rybh](https://github.com/kpi88/chatbot-docker/assets/77453174/48da7d40-78ef-46cd-a136-f7058b02403d)
